INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (1,'Café','Café preto 1 litro');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (2,'Suco','Suco del vale');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (3,'Pão','Pão de forma');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (4,'Bolo','Bolo de morango');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (5,'Pão de queijo','20 pães de queijo');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (6,'	Leite','1 litro de leite');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (7,'Queijo','500 gramas de queijo');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (8,'presunto','500 gramas de presunto');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (9,'Açúcar','500 gramas de açúcar');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (10,'Frutas frescas','Morangos,laranja,banana entre outros');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (11,'Manteiga','1 unidade de manteiga');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (12,'Iogurte','500 ml de iogurte');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (13,'Biscoitos','Biscoitos oreo');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (14,'Chá','500 ml de chá');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (15,'Geléia','1 unidade de geléia');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (16,'Peito de peru','500 gramas de peio de peru');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (17,'panqueca','algumas panquecas');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (18,'Mortadela','500 gramas de mortadela');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (19,'Ovo','Ovo mexido ou cozido');
INSERT INTO ITEM_CAFE_MANHA (id_item_cafe_manha,nome,descricao) VALUES (20,'Castanhas','500 gramas de castanhas');
